name: unimatrix
version: '1.0.1'
summary: https://github.com/will8211/unimatrix
description: |
  Python script to simulate the display from "The Matrix" in terminal. Uses half-width katakana unicode characters by default, but can use custom character sets. Accepts keyboard controls while running. Based on CMatrix. 
grade: stable
confinement: strict
apps:
  unimatrix:
    command: unimatrix
parts:
  unimatrix:
    plugin: python
    source: https://github.com/will8211/unimatrix.git
